#if !defined Packet2SmoothhybridFlow_h
#define Packet2SmoothhybridFlow_h

#include "simulator.h"
#include "event.h"

#include "hybrid/stdevstool.h"
#include "sink/logtoscilabtool.h"
#include "qss/qsstools.h"
#include "general/BaseSimulator.h"

#include "network/NetworkData/NetworkPacket.h"
#include "hybrid_network/hybridFlow.h"

/*
 * Receives discrete packets (inPort0).  Outputs HybridFlows (outPort0) containing a packet  and/or a continuous rate (d)
 * The continuous rate is calculated as the average rate of bits in the smoothing window. For now it is only QSS1 but in the future more coefficients could be calculated
 * The averaged rate is sent every smoothing window period unless the difference with the previously sent rate is less than rateDeltaMin
 *
 * This model acts as a bandwidth delay for packets. Delay should be applied before this model by the discrete 'pacektLinkDelay.h' or after by a continuous 'qss_delay'.
 * Contrary to the Packet2hybridFlow, this model sends the packet AFTER the bandwidth delay (i.e. WITH_LAST_BIT) as implemented in hybridizationLink
 */
class Packet2SmoothhybridFlow: public BaseSimulator {
    // Parameters
    std::string flowId; // flowId to be used for the hybridFlows. Must match packet->flowId. This could be taken from the incoming packet, but at the start it is unknown. If mutiple flowId are receive there should be multiple averages being tracked, etc.
    double inv_bandwidth_bits_s = -1; // inverse of capacity (bits/s) = 1/C
    double smoothingWindow; // in seconds
    double rateDeltaMin; // in bps

    // State variables for the fluid-flow
    double departureRate[10]={0}; // input rate generated by incoming packet (always equal to inLinkCapacity)
    double dropsRate[10]={0};
    double delay[10]={0};
    double lastSentRate;  // we keep the lastly sent to compare with rateDeltaMin
    double sigmaForNextRate;
    double sigmaForNextPkt;
    uint windowSum_bits; // sum of packet sizes during the window (to calculate the averaged rate)

    std::deque<std::shared_ptr<NetworkPacket>> packetQueue; // The application can send data faster than the link, so packets are queued in the outgoing NIC

    enum SEND_STATE{WAITING, SEND_RATE, SEND_PACKET};
    SEND_STATE sendState = WAITING;

public:

    static constexpr const char* HYBRIDIZED_FLOWS_ID = "__HYBRIDIZED_FLOW_ID"; //  hardcoded string shared with the hybridizedDemultiplexor

    Packet2SmoothhybridFlow(const char *n): BaseSimulator(n) {};
    void init(double, ...);
    void dint(double);
    void dext(Event , double );
    Event lambda(double);
private:
    std::shared_ptr<hybridFlow> createPacketHybridFlow();
    std::shared_ptr<hybridFlow> createFluidHybridFlow(double avgRate);
    double calculateWindowAverageRate(); // sum/window
    double calculateCurrentPacketBandwidthDelay(); // packetSize/BW
    void updateSigmas(double t);
    void setSigma();
};
#endif
