#if !defined Packet2HybridFlow_h
#define Packet2HybridFlow_h

#include "simulator.h"
#include "event.h"

#include "hybrid/stdevstool.h"
#include "sink/logtoscilabtool.h"
#include "qss/qsstools.h"
#include "general/BaseSimulator.h"

#include "network/NetworkData/NetworkPacket.h"
#include "hybrid_network/hybridFlow.h"

/*
 * Receives discrete packets (inPort0).  Outputs HybridFlows (outPort0) containing the packet  and a continuous rate (d)
 * The continuous rate d amplitude will be always equal to the incoming link capacity (C_in).
 * The signal will be sent for a period of time equal to packetSize/C_in
 *
 * If the host sends data fasted than the link bandwidth, packets are queued in this model (logged to 'queueSize' signal). It is better to use a proper PacketQueue.h that can drop, log, etc.
 *
 * This model acts as a bandwidth delay for packets.  Delay should be applied before this model by the discrete 'pacektLinkDelay.h' or after by a continuous 'qss_delay'.
 * Contrary to the hybridizationLink and Packet2SmoothFlow, this model sends the packet as soon as it arrives (i.e. WITH_FIRST_BIT as implemented in hybridizationLink) and LATER waits a bandwidth delay to process next packet. (packetDiscard) need the packet to be received before the signal
 */
class Packet2hybridFlow: public BaseSimulator {



    // Parameters
    double inv_bandwidth_bits_s = -1; // inverse of capacity (bits/s) = 1/C

    // State variables for the fluid-flow
    double departureRate[10]={0}; // input rate generated by incoming packet (always equal to inLinkCapacity)
    double dropsRate[10]={0};
    double delay[10]={0};
    double cero[10] = {0}; // this is to reset the input rate
    std::shared_ptr<hybridFlow> lastSentFlow; // we keep the lastly sent to compare an avoid sending useless QSS signals

    std::deque<std::shared_ptr<NetworkPacket>> packetQueue; // The application can send data faster than the link, so packets are queued in the outgoing NIC

    enum SEND_STATE{WAITING, SEND_INPUT_RATE, SEND_PACKET, SEND_INPUT_RATE_RESET};
    SEND_STATE sendState = WAITING;

public:

    static constexpr const char* HYBRIDIZED_FLOWS_ID = "__HYBRIDIZED_FLOW_ID"; //  hardcoded string shared with the hybridizedDemultiplexor

    Packet2hybridFlow(const char *n): BaseSimulator(n) {};
    void init(double, ...);
    void dint(double);
    void dext(Event , double );
    Event lambda(double);
private:
    double calculateCurrentPacketBandwidthDelay(); // packetSize/BW
    std::shared_ptr<hybridFlow> createHybridFlow(double* fluidRate);
};
#endif
