# Version: 0.1
# Date modified: 04/09/23

FROM centos:7
MAINTAINER James Maple <james.m@cern.ch>

# Environment setup
ARG USERNAME
ENV SCILAB_VERSION=5.5.2

# Fix CentOS 7 EOL mirrors (mirrorlist.centos.org is gone, use vault)
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*.repo \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo

# Install SCL and EPEL, then fix their vault URLs before using them
RUN yum install -y centos-release-scl epel-release \
    && sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-SCLo-*.repo \
    && sed -i 's|# baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-SCLo-*.repo \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-SCLo-*.repo \
    && sed -i 's|baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-SCLo-*.repo \
    && yum-config-manager --enable epel

RUN yum update -y \
    && yum upgrade -y \
    && yum install -y \
        make \
        git \
        boost-devel \
        devtoolset-7 \
        graphviz \
        wget \
        python-matplotlib \
        python-devel \
        h5py \
        qt-devel \
        gsl-devel \
        gnuplot \
        hdf5-devel \
        python-future \
        python-configparser \
        python-six \
        time-1.7 \
        python3  \
        python3-pillow \
        python3-tkinter \
        matplotlib \
        h5py \
        pandas \
        xeyes \
        libXScrnSaver \
        libXtst \
    && yum clean all -y \
    && pip3 install --upgrade pip \
    && pip3 install matplotlib h5py pandas


# Install scilab
WORKDIR /opt/rh
RUN wget http://www.scilab.org/download/$SCILAB_VERSION/scilab-$SCILAB_VERSION.bin.linux-x86_64.tar.gz -nv && \
    tar xzf scilab-$SCILAB_VERSION.bin.linux-x86_64.tar.gz && \
    rm -f scilab*.tar.gz && \
    ln -s /opt/rh/scilab-$SCILAB_VERSION/bin/scilab /usr/bin/scilab
WORKDIR /


# QT make
RUN ln -s /usr/bin/qmake-qt4 /usr/bin/qmake

# Add py2pdevs to the PythonPath
ENV PYTHONPATH "${PYTHONPATH}:/powerdevs/build/lib"
ENV LD_LIBRARY_PATH "${LD_LIBRARY_PATH}:/powerdevs/build/lib"

# X11 config
RUN groupadd -g 1000 ${USERNAME} && useradd -s /bin/bash -m ${USERNAME} -u 1000 -g 1000
USER ${USERNAME}

# Start
#ENTRYPOINT ["scl", "enable", "devtoolset-7", "bash"]
RUN echo "source scl_source enable devtoolset-7" >> /home/${USERNAME}/.bashrc
WORKDIR /powerdevs
