# Version: 0.1
# Date modified: 13/09/23

FROM centos:7
MAINTAINER James Maple <james.m@cern.ch>

# Environment setup
ARG USERNAME
ENV SCILAB_VERSION=5.5.2

# Update base image and install packages
RUN yum update -y \
    && yum upgrade -y \
    && yum install -y centos-release-scl epel-release \
    && yum-config-manager --enable epel \
    && yum update -y \
    && yum upgrade -y \
    && yum install -y \
        make \
        git \
        boost-devel \
        devtoolset-7 \
        graphviz \
        wget \
        python-matplotlib \
        python-devel \
        h5py \
        qt-devel \
        gsl-devel \
        gnuplot \
        hdf5-devel \
        python-future \
        python-configparser \
        python-six \
        time-1.7 \
        python3  \
        python3-pillow \
        matplotlib \
        h5py \
        pandas \
        xeyes \
	xorg-x11-server-utils \
	xauth \
	openssh-server \
    && yum clean all -y \
    && pip3 install --upgrade pip \
    && pip3 install matplotlib h5py pandas


# Install scilab
WORKDIR /opt/rh
RUN wget http://www.scilab.org/download/$SCILAB_VERSION/scilab-$SCILAB_VERSION.bin.linux-x86_64.tar.gz -nv && \
    tar xzf scilab-$SCILAB_VERSION.bin.linux-x86_64.tar.gz && \
    rm -f scilab*.tar.gz && \
    ln -s /opt/rh/scilab-$SCILAB_VERSION/bin/scilab /usr/bin/scilab
WORKDIR /


# QT make
RUN ln -s /usr/bin/qmake-qt4 /usr/bin/qmake


# Add py2pdevs to the PythonPath
ENV PYTHONPATH "${PYTHONPATH}:/powerdevs/build/lib"
ENV LD_LIBRARY_PATH "${LD_LIBRARY_PATH}:/powerdevs/build/lib"


# X11 / SSH config (Password: powerdevs)
RUN groupadd -g 1000 ${USERNAME} && useradd -s /bin/bash -m ${USERNAME} -u 1000 -g 1000
RUN ssh-keygen -A
RUN sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#Port 22/Port 2222/' /etc/ssh/sshd_config
RUN echo "root:powerdevs" | chpasswd
RUN echo "${USERNAME}:powerdevs" | chpasswd
ENV DISPLAY=:0



# Start
WORKDIR /powerdevs
EXPOSE 2222
ENTRYPOINT ["/usr/sbin/sshd", "-D"]






