#if !defined hybridizationLink_h
#define hybridizationLink_h

#include "simulator.h"
#include "event.h"

#include "hybrid/stdevstool.h"
#include "NetworkData/NetworkPacket.h"
#include "sink/logtoscilabtool.h"
#include "qss/qsstools.h"
#include "general/BaseSimulator.h"

/*
* Receives discrete packets (inPort0) and outputs the packet (outPort0) and a continuous inputRate (outPort1)
* The input rate amplitude will be always equal to the incoming link capacity (C_in).
* The signal will be sent for a period of time equal to packetSize/C_in
*
* The discrete packet is sent in outPort0. It could be sent either when 1) the FIRST bit is sent, or 2) when the LAST bit is sent.
* The signal and the packet are always sent in the same T. But other models (packetDiscard) need the packet to be received before the signal, so it is in the same T but fist the packet.
*
*
* If the host sends data fasted than the link packets are queued in this model (logged to 'queueSize' signal), although it is better to use a proper PacketQueue.h
*
*
* Delay should be applied before this model by the discrete 'pacektLinkDelay.h' or after by a continuous 'qss_delay'
*
*
*/
class hybridizationLink: public BaseSimulator {

// Parameters
double bandwidth_bits_s = -1; // capacity (bits/s)
enum DISCRETE_PACKET_SEND_MODE { WITH_FIRST_BIT, WITH_LAST_BIT};
DISCRETE_PACKET_SEND_MODE discretePacketSendMode;

// State variables
double sentInputRate[10] = {0}; // input rate generated by incoming packet (always equal to inLinkCapacity)
double cero[10] = {0}; // this is to reset the input rate
//double sentInputRateDuration = -1; // period of time for which the input rate will be sent. Equal to packetSize/inLinkCapacity

std::deque<std::shared_ptr<NetworkPacket>> packetQueue; // The application can send data faster than the link, so packets are queued in the outgoing NIC

enum SEND_STATE{WAITING, SEND_INPUT_RATE, SEND_PACKET, SEND_INPUT_RATE_RESET};
SEND_STATE sendState = WAITING;

std::map <std::pair<DISCRETE_PACKET_SEND_MODE, SEND_STATE>, SEND_STATE>  transitionTable;

public:
	hybridizationLink(const char *n): BaseSimulator(n) {};
	void init(double, ...);
	void dint(double);
	void dext(Event , double );
	Event lambda(double);
private:
	double calculateCurrentPacketBandwidthDelay(); // packetSize/BW
};
#endif
