FROM camisa/powerdevs_devel:latest

#ARG UNAME=testuser # only available after docker 1.9 (not compatible in CENTOS6) :-(

# eclipse
# from local file system
COPY eclipse-cpp-oxygen-3a-linux-gtk-x86_64.tar.gz /tmp/eclipse.tar.gz 

# download from web
# RUN wget http://eclipse.c3sl.ufpr.br/technology/epp/downloads/release/oxygen/3a/eclipse-cpp-oxygen-3a-linux-gtk-x86_64.tar.gz -O /tmp/eclipse.tar.gz

# install
RUN    echo 'Installing eclipse' && \
    tar -xf /tmp/eclipse.tar.gz -C /opt && \
    rm /tmp/eclipse.tar.gz

# prepare eclipse settings
ADD eclipse-workspace.tar.gz /opt/eclipse/
RUN chmod -R 777 /opt/eclipse
COPY org.eclipse.ui.ide.prefs /opt/eclipse/configuration/.settings/org.eclipse.ui.ide.prefs
#COPY org.eclipse.ui.ide.prefs /home/$USER/.eclipse/org.eclipse.platform_4.7.3_1473617060_linux_gtk_x86_64/configuration/.settings/org.eclipse.ui.ide.prefs
#RUN ln -s /opt/eclipse/eclipse /usr/bin/eclipse 
COPY eclipse.sh /usr/bin/eclipse 
RUN chmod +x /usr/bin/eclipse 

