######################################################################
# Automatically generated by qmake (2.01a) Wed May 27 17:16:02 2009
######################################################################

TEMPLATE = app
unix {
  TARGET = ../../bin/pdppt
}
win32 {
  TARGET = ../../../tmp_win_installer/powerdevs/bin/pdppt
}
DEPENDPATH += .
INCLUDEPATH += .

# Input
CONFIG += qt 
HEADERS += codegenerator.h \
           PythonCodeGenerator.h \
           modelatomic.h \
           modelchild.h \
           modelcoupled.h \
           modelparameter.h \
           parser.h
SOURCES += codegenerator.cpp PythonCodeGenerator.cpp modelchild.cpp main.cpp parser.cpp
RC_FILE = pdppt.rc

#debug - release
CONFIG(release, debug|release):DEFINES += QT_NO_DEBUG_OUTPUT