{
 "title": "tdaq_phase2_template",
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "1970-01-01T00:00:10.000Z" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "buckets()" },
   {
    "name": "core_router",
    "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"level0\"] =~ /core_router.*/)\n  |> keep(columns: [\"level0\"])\n  |> group()\n  |> distinct(column: \"level0\")"
   },
   {
    "name": "data_handler",
    "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"level0\"] =~ /DH.*/)\n  |> keep(columns: [\"level0\"])\n  |> group()\n  |> distinct(column: \"level0\")"
   }
  ]
 },
 "panels": [
  {
   "title": "HLTSV Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sent\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: 1s, fn: sum)"
    }
   ]
  },
  {
   "title": "Idle EF Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"idlePUs\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: 100ms, fn: mean)"
    }
   ]
  },
  {
   "title": "$data_handler TCP Congestion Window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "repeat": "data_handler",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cwnd\")\n  |> filter(fn: (r) => r[\"level0\"] == \"$data_handler\")\n  |> filter(fn: (r) => r[\"level1\"] == \"TcpSessions\")\n  |> filter(fn: (r) => r[\"level2\"] =~ /TCP_SND_.*/)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_time\", \"_value\", \"level2\"])"
    }
   ]
  },
  {
   "title": "$core_router Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "repeat": "core_router",
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"evCount\")\n  |> filter(fn: (r) => r[\"level0\"] == \"$core_router\")\n  |> filter(fn: (r) => r[\"level1\"] =~ /egressPort.*/)\n  |> filter(fn: (r) => r[\"level3\"] == \"elemSize\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_time\", \"_value\", \"level1\"])\n  |> aggregateWindow(every: 1s, fn: sum)"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"evCount\")\n  |> filter(fn: (r) => r[\"level0\"] == \"$core_router\")\n  |> filter(fn: (r) => r[\"level1\"] =~ /egressPort.*/)\n  |> filter(fn: (r) => r[\"level3\"] == \"elemSize\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_time\", \"_value\", \"level1\"])\n  |> aggregateWindow(every: 1s, fn: sum)\n  |> group(columns: [\"_time\"])\n  |> sum()\n  |> group(columns: [\"_time\", \"_value\"], mode: \"except\")"
    }
   ]
  },
  {
   "title": "$core_router Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "repeat": "core_router",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sum\")\n  |> filter(fn: (r) => r[\"level0\"] == \"$core_router\")\n  |> filter(fn: (r) => r[\"level1\"] =~ /egressPort.*/)\n  |> filter(fn: (r) => r[\"level2\"] == \"queue\")\n  |> filter(fn: (r) => r[\"level3\"] == \"elemSize\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_time\", \"_value\", \"level1\"])\n  |> aggregateWindow(every: 1s, fn: sum)"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sum\")\n  |> filter(fn: (r) => r[\"level0\"] == \"$core_router\")\n  |> filter(fn: (r) => r[\"level1\"] =~ /egressPort.*/)\n  |> filter(fn: (r) => r[\"level2\"] == \"queue\")\n  |> filter(fn: (r) => r[\"level3\"] == \"elemSize\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: 1s, fn: sum)\n  |> group(columns: [\"_time\"])\n  |> sum()\n  |> group(columns: [\"_time\", \"_value\"], mode: \"except\")"
    }
   ]
  },
  {
   "title": "Maximum DH Buffer Size",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"max\")\n  |> filter(fn: (r) => r[\"level0\"] =~ /DH.*/)\n  |> filter(fn: (r) => r[\"level1\"] == \"DHProcess\")\n  |> filter(fn: (r) => r[\"level2\"] == \"buffered_fragments_bytes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\", \"level0\"])"
    }
   ]
  },
  {
   "title": "Collected Event Size",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"collected_event_size_bytes\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "<",
   "type": "stat",
   "gridPos": { "h": 8, "w": 1, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"collected_event_size_bytes\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> min()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"collected_event_size_bytes\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> mean()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"collected_event_size_bytes\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> min()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"collected_event_size_bytes\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> max()"
    }
   ]
  },
  {
   "title": "Data Collection",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data_collection_ms\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "<",
   "type": "stat",
   "gridPos": { "h": 8, "w": 1, "x": 23, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data_collection_ms\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> min()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data_collection_ms\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> mean()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data_collection_ms\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> stddev()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data_collection_ms\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> max()"
    }
   ]
  },
  {
   "title": "^",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 8, "query": "buckets()" }
   ]
  },
  {
   "title": "Filter Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"filter_latency_ms\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "<",
   "type": "stat",
   "gridPos": { "h": 8, "w": 1, "x": 11, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"filter_latency_ms\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> min()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"filter_latency_ms\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> mean()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"filter_latency_ms\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> stddev()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"filter_latency_ms\")\n  |> filter(fn: (r) => r[\"level0\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"level1\"] == \"HLTSV\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> max()"
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"networkLatency_ms\")\n  |> filter(fn: (r) => r[\"level0\"] =~ /EF.*/)\n  |> filter(fn: (r) => r[\"level1\"] == \"DCM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\", \"level0\"])"
    }
   ]
  },
  {
   "title": "<",
   "type": "stat",
   "gridPos": { "h": 8, "w": 1, "x": 17, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"networkLatency_ms\")\n  |> filter(fn: (r) => r[\"level0\"] =~ /EF.*/)\n  |> filter(fn: (r) => r[\"level1\"] == \"DCM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> min()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"networkLatency_ms\")\n  |> filter(fn: (r) => r[\"level0\"] =~ /EF.*/)\n  |> filter(fn: (r) => r[\"level1\"] == \"DCM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> mean()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"networkLatency_ms\")\n  |> filter(fn: (r) => r[\"level0\"] =~ /EF.*/)\n  |> filter(fn: (r) => r[\"level1\"] == \"DCM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> stddev()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"networkLatency_ms\")\n  |> filter(fn: (r) => r[\"level0\"] =~ /EF.*/)\n  |> filter(fn: (r) => r[\"level1\"] == \"DCM\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> keep(columns: [\"_value\"])\n  |> max()"
    }
   ]
  },
  {
   "title": "DH Process Time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_time\")\n  |> filter(fn: (r) => r[\"level0\"] =~ /DH.*/)\n  |> filter(fn: (r) => r[\"level1\"] == \"DHProcess\")\n  |> keep(columns: [\"level0\", \"_value\"])"
    }
   ]
  },
  {
   "title": "<",
   "type": "stat",
   "gridPos": { "h": 8, "w": 1, "x": 23, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_time\")\n  |> filter(fn: (r) => r[\"level0\"] =~ /DH.*/)\n  |> filter(fn: (r) => r[\"level1\"] == \"DHProcess\")\n  |> keep(columns: [\"_value\"])\n  |> min()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_time\")\n  |> filter(fn: (r) => r[\"level0\"] =~ /DH.*/)\n  |> filter(fn: (r) => r[\"level1\"] == \"DHProcess\")\n  |> keep(columns: [\"_value\"])\n  |> mean()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_time\")\n  |> filter(fn: (r) => r[\"level0\"] =~ /DH.*/)\n  |> filter(fn: (r) => r[\"level1\"] == \"DHProcess\")\n  |> keep(columns: [\"_value\"])\n  |> stddev()"
    },
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_time\")\n  |> filter(fn: (r) => r[\"level0\"] =~ /DH.*/)\n  |> filter(fn: (r) => r[\"level1\"] == \"DHProcess\")\n  |> keep(columns: [\"_value\"])\n  |> max()"
    }
   ]
  }
 ]
}